// auth action types
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const ADD_DISH_TO_CART = "ADD_DISH_TO_CART";
export const REMOVE_DISH_FROM_CART = "REMOVE_DISH_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const ADD_DISH_START = "ADD_DISH_START";
export const ADD_DISH_FAILURE = "ADD_DISH_FAILURE";
export const ADD_DISH_SUCCESS = "ADD_DISH_SUCCESS";
export const GET_DISHES_START = "GET_DISHES_START";
export const GET_DISHES_SUCCESS = "GET_DISHES_SUCCESS";
export const GET_DISHES_FAILURE = "GET_DISHES_FAILURE";

export const POST_ORDER_START = "POST_ORDER_START";
export const POST_ORDER_FAILURE = "POST_ORDER_FAILURE";
export const POST_ORDER_SUCCSS = "POST_ORDER_SUCCSS";
